apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: simple-rest-server
  name: simple-rest-server-hpa-external
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-rest-server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: "YOUR_METRIC_NAME"
        target:
          type: Value
          value: "YOUR_VALUE"
