apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "gce"
  labels:
    app: simple-rest-server
  name: simple-rest-server-ingress
spec:
  rules:
    - host: "YOUR_DOMAIN"
      http:
        paths:
          - backend:
              service:
                name: simple-rest-server-service
                port:
                  name: http
            path: /*
            pathType: ImplementationSpecific
