apiVersion: v1
kind: Service
metadata:
  name: simple-rest-server-service
  labels:
    app: simple-rest-server
spec:
  type: ClusterIP
  selector:
    app: simple-rest-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: http-port
    name: http