apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: nginx
  name: nginx-hpa-external-reducer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: "loadbalancing.googleapis.com|https|request_count"
          selector:
            matchLabels:
              resource.labels.url_map_name: "k8s2-um-4vubmsmu-default-nginx-ingress-91yjparm"
              reducer: "REDUCE_PERCENTILE_99"
        target:
          type: AverageValue
          value: "50000m"