apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: nginx
  name: nginx-hpa-external
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: "YOUR_METRIC"
          selector:
            matchLabels:
              resource.labels.url_map_name: "YOUR_URL_MAP_NAME"
        target:
          type: AverageValue
          value: "YOUR_VALUE"
